#platform :ios, '10.0'
use_frameworks!
target 'CityListExport' do
    platform :ios, '10.0'

    pod 'Kanna', '~> 2.1.0'
    pod 'SwiftyJSON', '~> 3.1'

end
post_install do |installer|
    oldSwiftTargets = ['Toast-Swift', 'StatefulViewController', 'Kanna', 'SwiftyJSON', 'GDPerformanceView-Swift']
    installer.pods_project.targets.each do |target|
        if oldSwiftTargets.include? target.name
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
